### ISSUE TITLE
transform

### ISSUE THREAD

**Issue by burin** [brandonaaron/jquery-cssHooks#12]
Helpful reference:

http://compass-style.org/docs/reference/compass/css3/transform/

**Comment by brandonaaron** [comment]
Also a rotate cssHook: https://github.com/lrbabe/jquery.rotate.js/blob/master/jquery.rotate.js

**Comment by louisremi** [comment]
I'm currently working on a complete transform hook.
I figured out that the only way to implement getters is to keep track of each transformation.

**Comment by burin** [comment]
added:
https://github.com/brandonaaron/jquery-cssHooks/commit/d16c96135900b6d7701a1b0520213b7c4e1346a4
