### ISSUE TITLE
Border Radius 

### ISSUE THREAD

**Issue by dtm5011** [brandonaaron/jquery-cssHooks#25]
Setting border radius has no effect in firefox 3.6.

**Comment by louisremi** [comment]
Can you show us a reduced test case at http://jsfiddle.net ?

Regards,

Louis-Rémi

**Comment by dtm5011** [comment]
I created test case http://jsfiddle.net/JSFUe/ and it seems everything works correctly.  It turns out my problem was that I was using version 1.4.2 of jquery.  My apologies.  

Keep up the good work,

Dave
