### ISSUE TITLE
Update our hooks

### ISSUE THREAD

**Issue by tomgrohl** [brandonaaron/jquery-cssHooks#39]
It's been a while since we did some work on our hooks.

Is it time we updated them?

I'm dropping support for my border radius hook. IE hack is stupid. We won't have 2 hooks for the same thing then.

Let ne know your thoughts

Tom.

**Comment by brandonaaron** [comment]
A year later... Probably not a bad idea to re-evaluate this project. Figure out what is still needed and what isn't.

Also thinking about wrapping each hook in a UMD wrapper so it can be easily loaded with the various module loaders.

**Comment by tomgrohl** [comment]
Wow its been a while. Yes totally agree with that. I'll close this, as we can discuss everything in #42
