### ISSUE TITLE
border-radius

### ISSUE THREAD

**Issue by brandonaaron** [brandonaaron/jquery-cssHooks#5]
http://twitter.com/ajpiano/status/29401830944

**Comment by brandonaaron** [comment]
Can even allow a user to configure a plugin to use for rounded-corners in IE, should the user want to do that.

**Comment by burin** [comment]
added two versions:
https://github.com/brandonaaron/jquery-cssHooks/commit/fd98feff1e1fe5e59ee2bb00d8a033bf4e236fc4

Alt:
https://github.com/brandonaaron/jquery-cssHooks/commit/e720fd9fb7b29ae565d87a7b736ade2084ec24c0
