### ISSUE TITLE
Background image gradients

### ISSUE THREAD

**Issue by brandonaaron** [brandonaaron/jquery-cssHooks#6]
http://twitter.com/b4nn0n/status/29402831548

Definitely a good one. Might want to use a custom property name... maybe "linearGradient" for a linear gradient instead of trying to deal with parsing out the background-image property (which would be a nightmare).

**Comment by darcyclarke** [comment]
+1 On this. Was thinking about writing this last night.

**Comment by tomgrohl** [comment]
Closing as this already exists: https://github.com/brandonaaron/jquery-cssHooks/blob/reorg/src/gradients/gradients.js

It needs re-testing and a bit of a rewrite but that will be done soon.

**Comment by brandonaaron** [comment]
Thanks Tom! Hopefully I can make some time to jump back on this project soon-ish as well.
